### ISSUE TITLE
Visium multiple slides

### ISSUE THREAD

**Issue by spatialbiology1** [YangLabHKUST/SpatialScope#1]
Thanks so much for the great tool! Can we integrate multiple slides from primary and metastatic samples.? I am analyzing N= 30 samples from primary tumor, lymph nodes and lung metastasis.
Many thanks
Zinn

**Comment by JiaShun-Xiao** [comment]
Hi, Zinn,

It is feasible to apply our tool to multiple samples by analyzing one ST sample at a time.
In this way, we will separately account for batch effects between the scRNA-seq reference and each ST sample, making cell type identification results immune to batch effects (both among ST samples and between ST and scRNA-seq ref) and consistent across multiple samples.

best wishes,
Jiashun
