### ISSUE TITLE
scRNA-seq reference integration

### ISSUE THREAD

**Issue by ChenJin2020** [YangLabHKUST/SpatialScope#8]
Hi,

I am currently conducting research on ovarian tissue using 10x single-cell RNA sequencing (scRNA-seq) datasets. However, these datasets do not include oocytes, which are crucial for my study. To address this, I plan to integrate my 10x scRNA-seq datasets with publicly available scRNA-seq datasets of oocytes, which were generated using the SMART-seq2 method. My question is about handling the differences in data resolution and depth between these two methods. Specifically, when I use the combined datasets as a reference in my research, should I downsample the SMART-seq2 oocyte datasets to match the resolution of the 10x scRNA-seq datasets? I'm concerned about potential biases or discrepancies in data interpretation due to the different sequencing depths and resolutions of these methods. Any guidance on this integration process would be greatly appreciated.

Thanks,

Chen

**Comment by JiaShun-Xiao** [comment]
> Hi,
> 
> I am currently conducting research on ovarian tissue using 10x single-cell RNA sequencing (scRNA-seq) datasets. However, these datasets do not include oocytes, which are crucial for my study. To address this, I plan to integrate my 10x scRNA-seq datasets with publicly available scRNA-seq datasets of oocytes, which were generated using the SMART-seq2 method. My question is about handling the differences in data resolution and depth between these two methods. Specifically, when I use the combined datasets as a reference in my research, should I downsample the SMART-seq2 oocyte datasets to match the resolution of the 10x scRNA-seq datasets? I'm concerned about potential biases or discrepancies in data interpretation due to the different sequencing depths and resolutions of these methods. Any guidance on this integration process would be greatly appreciated.
> 
> Thanks,
> 
> Chen

Hi,

We have not yet attempted to integrate the 10x and SMART-seq2 single-cell datasets. But we think it is okay to do this, and ideally the sequencing depth issue can be solved through normalize_total preprocessing. You could try using the integrated single cell reference for "cell type identification" and see if the oocytes in your spatial data are correctly identified. If this step is successful, the integrated single-cell reference is totally fine.

Thanks,
Jiashun

**Comment by ChenJin2020** [comment]
> > Hi,
> > I am currently conducting research on ovarian tissue using 10x single-cell RNA sequencing (scRNA-seq) datasets. However, these datasets do not include oocytes, which are crucial for my study. To address this, I plan to integrate my 10x scRNA-seq datasets with publicly available scRNA-seq datasets of oocytes, which were generated using the SMART-seq2 method. My question is about handling the differences in data resolution and depth between these two methods. Specifically, when I use the combined datasets as a reference in my research, should I downsample the SMART-seq2 oocyte datasets to match the resolution of the 10x scRNA-seq datasets? I'm concerned about potential biases or discrepancies in data interpretation due to the different sequencing depths and resolutions of these methods. Any guidance on this integration process would be greatly appreciated.
> > Thanks,
> > Chen
> 
> Hi,
> 
> We have not yet attempted to integrate the 10x and SMART-seq2 single-cell datasets. But we think it is okay to do this, and ideally the sequencing depth issue can be solved through normalize_total preprocessing. You could try using the integrated single cell reference for "cell type identification" and see if the oocytes in your spatial data are correctly identified. If this step is successful, the integrated single-cell reference is totally fine.
> 
> Thanks, Jiashun

Hi,
I am currently preparing my single-cell RNA-seq data for analysis with SpatialScope, and according to the provided guidance, it seems necessary to perform a comprehensive analysis using Scanpy, including steps such as normalization, PCA, and UMAP, to generate the appropriate input file. My dataset was initially analyzed with Seurat, and I have detailed cell type annotations from this prior analysis. I am seeking clarification on whether it is feasible to integrate these Seurat-derived cell type annotations into a new Anndata object created with Scanpy. Specifically, my plan is to:

Create an Anndata object with my gene expression matrix.
Add the cell type information from the Seurat analysis to the Anndata's metadata.
Proceed with the normalization step in Scanpy.
Would this approach be valid for preparing my data for SpatialScope? My aim is to leverage the cell type information I have without redoing the entire clustering and annotation process. After normalization, I intend to save this as an h5ad file and use it as the input for SpatialScope. Could you please advise if this method aligns with the requirements for SpatialScope, or if there are additional steps I should take to ensure compatibility?

Thanks,

Chen

**Comment by ChenJin2020** [comment]
Thank you
